app1/urls.py
from django.urls import path
from app1.views import *
app_name='detergent'

urlpatterns=[
    path('first/',first,name='first'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='soap'

urlpatterns=[
    path('second/',second,name='second'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
from app2.views import *
import app1,app2


urlpatterns = [
    path("admin/", admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'ujala.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def second(request):
    return render(request,'xxxsoap.html')

templates/ujala.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <center>
        <h1><a href="{% url 'soap:second' %}">XXX Soap</a></h1>
        <h2>kotta Samskara vantamaina soap</h2>
    </center>
</body>
</html>

templates/xxxsoap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <center>
        <h1><a href="{% url 'detergent:first' %}">ujala</a></h1>
        <h2>
            Washing powder Nirma
        </h2>
    </center>
</body>